### ISSUE TITLE
Use Highlights.jl where possible instead of highlight.js

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#104]
**Edit**: ignore this first few comments and scroll directly to https://github.com/tlienart/JuDoc.jl/issues/104#issuecomment-475570629_

What we could do is

1. detect code blocks
2. call a function on the content of the code block that finds keywords, strings, numbers etc
3. output id'd HTML elements
4. have styling in CSS

Since it may be annoying/hard to provide this for every possible language, we could have standard config file for Julia to copy which just keeps track of the keywords that the user want to highlight.

Advantages as mentioned in https://github.com/tlienart/JuDoc.jl/issues/103#issuecomment-469428255_ it could slim down pages further by removing the dependency on highlight.js. Possibly it could still be a "backend" for users who want snippets of code in another language and just want to use an off-the-shelf tool.

**Comment by asprionj** [comment]
We could just use highlight.js offline / at the HTML-generation step. Implementing syntax-highlighting from scratch sounds like a bad idea, since it's a widely "solved" problem. How does Juno/Atom do it? And Documenter.jl?

Or just extract the relevant parts (and CSS) from [Pygments](http://pygments.org/), [Prism](https://prismjs.com/), ...

**Comment by tlienart** [comment]
I definitely agree with the "it's already a solved problem" but I'm not sure I'm with you in terms of how to do it (e.g. how to capture the html that highlight generates or do that pass "offline") but if you have an idea give it a shot and we can compare :) 

All of these systems including Juno/Atom at the base have the same kind of idea: they recognise keyword and then apply some style sheet on them, Atom/Juno don't use CSS but some json thing I think (not sure). The part of recognising a set of keywords is easy for JuDoc and takes negligible time, the style sheet could indeed be copied from highlight or prism (btw highlight does a better job at julia than prism). 

anyway to make it short:

1. I'm not sure how you'd do it offline without reimplementing it
2. I don't think reimplementing it would be hard (but maybe it's not the most useful thing to do right now).

**Comment by tlienart** [comment]
Probably just this: https://juliadocs.github.io/Highlights.jl/stable/man/guide.html#User-Guide-1 :)

**Comment by tlienart** [comment]
Ok so I've now integrated `Highlights.jl` but it's currently not used. Reasons for that:

1. modifying the CSS aspect is not directly trivial (but I admit I didn't spend much time to try to tweak it)
1. if a user shows code that is not supported by Highlights.jl, I feel there should be a fall-back on higlight.js but to make the CSS match would require a bit of fiddling, I may try to get one style to match
1. a somewhat easier possibility would be to completely ditch `highlight.js` and just tweak the CSS of `Highlight.jl` until it looks nice (for all themes!) and just assume that displayed code will be one of the supported language but, for instance, python is not yet in there. That could maybe encourage people to port the python pygment lexer to Highlights.jl

I'm thinking that, for now, we can stick with `highlight.js` while keeping in mind it's doable to just use Highlights.jl but I'm open to suggestions. Moving this to low-priority though as "it works" and is not too much of a performance drain.
