### ISSUE TITLE
Chase non-windows-friendly elements

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#105]
While both Linux and Mac should be fine to run JuDoc, I think some stuff will fail on windows:

* path-functions --> should be cleaned up to systematically use `joinpath` and avoid assumptions of forward slashes
* PID management --> not sure how that works on windows, probably should just disable it 🤷‍♂️ 

If someone sees this issue, has windows, and is willing to help, write here!

**Comment by asprionj** [comment]
I do have the possibility to try stuff under Windows (10). Always short on time, but will surely get to it at some point...

**Comment by tlienart** [comment]
I think I chased down most hardcoded  "unix-like" paths things so it should now be good to go on Windows. One thing that I suspect may fail is the PID management to kill node properly. I'll probably need to try this myself and borrow a windows box to see what can be done.

**Comment by tlienart** [comment]
tested on a windows 10 VM, required only one fix with an `escape_string` in a Regex but it otherwise works as expected. I have not tried the optimize step which requires installing `node` etc and the VM I have access to is very slow.
