### ISSUE TITLE
Other possible (grav) themes

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#112]
## Most in line with the philosophy

* [x] ~~https://demo.matthiasdanzinger.eu/vela/~~ (see #114 )
* [ ] http://hyde.getpoole.com/
* [ ] hugo acad theme http://kshyatt.github.io/ (Note: ask first if she's happy with repurposing, it's based on the Hugo Academic theme so probably fine but still.)
* [ ] something like this one: https://lawler.io/ though not the comments on the side
* [ ] some of this css https://github.com/kognise/water.css 

### GIT (1/2)

* https://demo.hibbittsdesign.org/grav-learn2-git-sync/ 

It's a bit of a slow beast though so might need some slimming. However the search thing is potentially nice. The buttons to navigate to next page may be nice too. 

also https://learn.getgrav.org/15 

### twenty fifteen

* https://demo.getgrav.org/twentyfifteen-skeleton/en

(may require some work to get the archival stuff, could remove it to begin with)

### striped

* https://demo.getgrav.org/striped-skeleton/

essentially the same as 2015

### saturn

* https://demo.getgrav.org/saturn-skeleton/ 

### HPSTR

the one page design is a bit shit but some people may like it (the hamburger menu is nice)

* https://demo.getgrav.org/hpstr-skeleton/

### Cacti

* https://demo.getgrav.org/multilang-skeleton/en/blog/an-example-post

nice and clean

### Tivka

* https://tikva-demo.kuerbis.org/ 

does not seem responsive.

**Comment by asprionj** [comment]
Agree on the first three; with them (and pure-sm) we'll have a nice collection of themes / layouts for different types of sites.

* GIT (1/2): a bit "crowded", and obviously intended for linear courses (with the prominent forward/backward arrows). Do we really need that?
* **twenty fifteen: very nice and clean. If it's not too much work, would be a great addition!**
* striped: don't see anything special in this one, and personally don't like the looks...
* **saturn: looks nice, and definitely different than "all the others". +1**
* HPSTR: I agree, no structure at all probably does not suit our use case
* Cacti: like it, but isn't it quite similar to the pure-sm?
* Tivka: nothing special IMHO

**Comment by tlienart** [comment]
Cool, thanks! I'll go with the ones you highlighted, no need for very many at the start, I think if we have 4-5 that are good and well integrated, it's already nice! and then we could imagine letting other people contributing. Now that I've ported one I think it will take me little time to port other ones 🙂

**Comment by tlienart** [comment]
Closing here, tracked [there](https://github.com/tlienart/JuDocTemplates.jl/issues/2)
