### ISSUE TITLE
SVGs not displaying locally

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#141]
I really like this! I'm in the process of transferring to it, but there's one problem I'm seeing. It may not be a problem with JuDoc at all, of course, but you might know...

When running/testing locally with `serve()`, SVG images aren't being displayed. This markup:

`![svg images](/assets/images/image.svg)`

works fine for PNGs, but not for SVGs. It occurred to me that it might be something to do with the server? In which case, the problem should go away when uploaded...

**Comment by cormullion** [comment]
I now think it's the server that doesn't show SVGs locally, so I'll close this... :)

**Comment by tlienart** [comment]
Great! let me know if I can help.

Re SVG, please let me know as I also had a few issues in the past though it seems unrelated to JuDoc. One potential problem is that the `![svg image](path/img.svg)` gets converted by `Base.Markdown` into a `<img ...>`. This seems to always work on firefox, but not always on chrome and safari but it seems to depend on the SVG itself. 

For instance SVG generated with PyPlot have caused me troubles in the past whereas I've generated SVG with other programs that showed fine.

When you say the server you mean LiveServer? and that it shows when you put the website online?

Thanks for the feedback!

**Comment by tlienart** [comment]
It seems we looked at the same stackoverflow page. I'm writing an issue on LiveServer, the bug comes from upstream though (HTTP.jl). Thanks for reporting! hopefully it'll be fixed soon.

**Comment by tlienart** [comment]
This is now fixed, a patch release of LiveServer has been tagged and should be live soon, you'll just have to `up` :)

**Comment by cormullion** [comment]
This works perfectly now! Thanks everyone :)
