### ISSUE TITLE
(macOS) Really ignore .DS_Store files? 

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#142]
You already check for those pesky `.DS_Store` files on macOS, but it looks like they're developing resistance...

```
julia-1.1> serve(verb=true, clear=true)
→ Initial full pass... 

✔ full pass...                         [done 82.7ms]

→ Starting the server...
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
→ file /src/index.md was modified → updating...  [done  1.4ms]
tracking new file '.DS_Store'.
^C
julia-1.1> serve(verb=true, clear=true)
→ Initial full pass... 

... error processing '.DS_Store' in ...ub.io/cormullion/src.
Verify, then start judoc again...

err = UndefVarError(:ts)
-1

julia-1.1> 
```

**Comment by tlienart** [comment]
Oh interesting! it's explicitly checked in the `src/pages` but not in just `src/`, good catch, thanks!

I've just fixed it in a branch and will merge it in a few minutes

**Comment by tlienart** [comment]
PS: I noticed you're using the `Vela` template, I was working on it yesterday and realised the navigation menu doesn't like to be minified so bear that in mind :) this is also unrelated to judoc but rather seems to be an issue with the python library I use for minification.
