### ISSUE TITLE
Logo/icon ideas

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#148]
Here are a few ideas for logos/icons to get started. If any of them take your fancy, suggest some directions to take them forward. I've kept to the Julia colorscheme for now, since that seems to be the thing...

<img width="463" alt="Screenshot 2019-05-05 at 11 57 31" src="https://user-images.githubusercontent.com/52289/57192880-44cce180-6f2d-11e9-924c-5f357258cf6c.png">

**Comment by asprionj** [comment]
Hrm, since it's about *technical* documentation, maybe work with cogwheels? E.g. [like this](https://www.iconfinder.com/icons/3421486/control_document_document_management_document_with_gear_symbol_documentation_plan_engineering_document_icon), but with three julia-coloured wheels and the document only indicated in the background (in light grey or something)?

**Comment by cormullion** [comment]
Yes, I've done cogwheel action before...

![julia-gears](https://user-images.githubusercontent.com/52289/57195570-3d690080-6f4c-11e9-8dd4-bc1a56c147c9.gif)

However, the idea has already been used to good effect by the https://github.com/JuliaInterop org. And it is a well-worn cliché too, so worth avoiding for that reason as well?

**Comment by asprionj** [comment]
Hehe, the wheels look cool. Ok, JuliaInterop has the three wheels. So what about a single wheel in the background and three julia-coloured documents in the foreground (possibly "connected" by the wheel?). Or the three documents in a "cycle of arrows" to illustrate the (fast) iterative workflow of JuDoc?

**Comment by asprionj** [comment]
Q&D illustration of the last idea:
![JuDoc_logo](https://user-images.githubusercontent.com/13935112/57197936-3d2d2d00-6f6d-11e9-8e64-b1262c751251.png)

**Comment by cormullion** [comment]
That's great!

**Comment by asprionj** [comment]
How about this version? Any suggestions for further improvements? Smaller "documents" to make the circle more prominent?

![JuDoc_logo svg](https://user-images.githubusercontent.com/13935112/57199701-36f57b80-6f82-11e9-9ae2-f1c57c0dae40.png)

**Comment by asprionj** [comment]
Ok, getting closer I think:

![JuDoc_logo_lighter svg](https://user-images.githubusercontent.com/13935112/57200132-ed0f9400-6f87-11e9-8ece-ff0aa10a45ff.png)

**Comment by asprionj** [comment]
Ok, one more; could not get the cogwheel out of my head. This one is not really "clean" yet, but illustrates the idea:

![cogwheel svg](https://user-images.githubusercontent.com/13935112/57200545-c2c0d500-6f8d-11e9-8d47-47efbe2f3675.png)

**Comment by tlienart** [comment]
Wow all this is great, thanks both! @asprionj I must admit I prefer the circle with the 3 docs rather than the cogwheel one. @cormullion I quite liked your central one (The J's in  a circle) but I fear it's a bit too Julia generic?

**Comment by cormullion** [comment]
Yes, it’s a familiar problem with logo design, whether to go ‘swoosh’ or ‘wrench’: https://pivotmarketing.com/4-things-logo-doesnt/
