### ISSUE TITLE
Weird behaviour of backticks inside html codeblock.

### ISSUE THREAD

**Issue by Invarianz** [tlienart/JuDoc.jl#151]
I have the following issue, where I am trying to document a julia function that has a docstring documentation attached to it.
````julia
"""
    bar(x[, y])

Compute the Bar index between x and y. If y is missing, compute
the Bar index between all pairs of columns of x.

# Examples
```jldoctest
```
"""
function bar(x, y)
    ...
end
````
In JuDoc I document this by using a raw html block. Otherwise the triple backticks of the docstring will clash with the JuDoc code markdown environment.
~~~~
~~~
<pre><code class="julia">
...
</code></pre>
~~~
~~~~
When I insert the above code with docstring into this html block I get the expected output plus this weird artefact:
````julia
"""
    bar(x[, y])

Compute the Bar index between x and y. If y is missing, compute
the Bar index between all pairs of columns of x.

# Examples
```jldoctest
```
"""
function bar(x, y)
    ...
end
````
""" function bar(x, y) ... end </code></pre> ~~~

**Comment by tlienart** [comment]
Hello,

Sorry for the delay, I was away over the last 10 days. 

Thanks a lot for reporting this and apologies for the bug. It's now fixed and will be merged into master shortly. 

This:

````
# How to use JuDoc

~~~
<pre><code class="julia">
"""
    bar(x[, y])

Compute the Bar index between x and y. If y is missing, compute
the Bar index between all pairs of columns of x.

# Examples
```jldoctest
```
"""
function bar(x, y)
    ...
end
</code></pre>
~~~

This section is meant as a refresher if you're new to JuDoc. ...
````

leads to what I think is what you expected:

![Screen Shot 2019-05-20 at 2 36 02 pm](https://user-images.githubusercontent.com/10897531/57996881-442b7200-7b0d-11e9-8ca7-ddaed707f707.png)

**Comment by Invarianz** [comment]
So at first it seemd the problem was fixed, but now there is a new issue appearing. The html code tags are now showing up in the first code block of the compiled document. I will attach the relevant markdown code.
[julia.txt](https://github.com/tlienart/JuDoc.jl/files/3199399/julia.txt)
Here is the wrong output:
![Screenshot_2019-05-20 Julia](https://user-images.githubusercontent.com/24905747/58045403-abafe480-7b42-11e9-8fb3-bbbb0a20cc33.png)

Strangely enough I can now leave the HTML code tags out in the first code block and make it work that way. However, this does not seem to be intendend behaviour.

**Comment by tlienart** [comment]
Ha shit I wrote the previous fix too quickly... apologies! this should now be _properly_ fixed. Thanks a lot for the reproducing example. The fix is available on #master. 

PS: one side note unrelated to JuDoc is that you may want to write your opening `"""` on the same line as `<code class="julia">` so that no spurious empty line is added at the top (this is the normal behaviour of a `<pre>` block). So for the screenshot below I used:

```markdown
# Documentation of functions
For simple functions with small number of arguments a short description in one
sentence is considered enough. How to provide examples can be seen in the next
problem.

~~~
<pre><code class="julia">"""
    bar(x[, y])

Compute the Bar index between x and y. If y is missing, compute
the Bar index between all pairs of columns of x.

# Examples
```jldoctest
D
```
"""
function bar(x, y)
    ...
end
</code></pre>
~~~
```

![Screen Shot 2019-05-21 at 12 21 03 pm](https://user-images.githubusercontent.com/10897531/58063784-fffaa900-7bc2-11e9-8db7-1323b07e04b9.png)

**Comment by tlienart** [comment]
(leaving this open until you confirm it works as expected)

**Comment by Invarianz** [comment]
Everything seems to work as expected, thanks for the quick fix!
