### ISSUE TITLE
Ctrl + c does not stop serve() on windows

### ISSUE THREAD

**Issue by danmrc** [tlienart/JuDoc.jl#154]
Hi,

I am using this package and I followed the manual and tried to stop `serve()` using ctrl + c and it did not work. It really does nothing at all. I tried both on atom and on the console. I am using windows 10 and Julia 1.1.

Besides that, I would like to suggest two things:

1. Anti virus do not like this package. I am using a computer with Avast and using `serve()` and I could not open the site on localhost:8000 (I tried other ports as well). It keeps loading forever and does not even return an error that it could not be reached. White listing the folder where JuDoc is installed solved the problem. Might be useful for other windows users.

2. If you don't set the directory created by the `newsite` as the working directory, the  `serve()`command returns an "unknown error". When you run the `newsite` it looks like it changes the working directory. While I am not sure if the error message could be improved, this might be addressed in the documentation

This is a really good package!

Thanks

**Comment by tlienart** [comment]
Hello Daniel, thanks a lot for reporting!

With respect to your second suggestion, yes you have to be inside the `website/` directory in order for `serve()` to work. I agree that a clearer error message should be thrown if that's not the case & I'll open an issue to fix that. Thanks!

### CTRL+C and avast

I believe these issues have to do with [`LiveServer.jl`](https://github.com/asprionj/LiveServer.jl), to make sure could you please try the first block of code in the readme: https://github.com/asprionj/LiveServer.jl and report whether CTRL+C interrupts the server properly? If not, could you please open an issue there and I'll try to figure it out there with you?

The issue with your anti-virus also has to do with LiveServer but given I both don't have windows nor avast it's a bit of poking in the dark, could you report whether one of those does the job: 

* https://forum.avast.com/index.php?topic=200552.0 
* https://stackoverflow.com/questions/19392087/cant-connect-to-localhost-after-avast-antivirus-latest-update

Also, you seem to say that just entering the address of the files in your browser works? Does everything work fine? (CSS, KaTeX etc?)

Thanks!

**Comment by tlienart** [comment]
@danmrc could you update me on whether you were able to try the example from LiveServer? thanks!

**Comment by danmrc** [comment]
Sorry for the delay, I only have Windows on the desktop.

After some use I've discovered that the interrupt works erratic. Sometimes it does work. Sometimes it doesn't. It doesn't matter if I am using Atom or the terminal. 

I tried the example of the liveserver. Ctrl + c throws a fatal error and crashes Julia. I guess I should open an issue there. 

On avast: both links deal with Avast security suite. I was not clear on it, but I have the free version. I don't have the avast firewall (first link) and I could connect to Jupyter Notebooks (which also uses a localhost). I tried changing the windows firewall configuration and it didn't work. I tried changing the port to the same port of Jupyter, which also didn't work. What did work was whitelisting _the package directory_. This is a relatively new install (less then a year), so I guess this is a trouble with avast. (On a side note,  shortly after this happened avast decided that Julia was a virus)

**Comment by tlienart** [comment]
Thanks for reporting, I've opened an issue on LiveServer (https://github.com/asprionj/LiveServer.jl/issues/78) if you could copy paste the error messages you have seen + explain your problems there, that would be very helpful!

I'm not sure how quickly I'll be able to fix them as on my Windows VM everything seems to work as it should 😕 but I think Jonas also has access to a windows 10 machine so maybe he'll be able to chip in.

I'm closing this here as it's not related to JuDoc but hope we can fix this in LiveServer. Cheers!
