### ISSUE TITLE
[FR] support for RSS (e.g. JuliaBloggers)

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#161]
Just a question really. How do RSS feeds work with JuDoc sites?

**Comment by tlienart** [comment]
Short answer: not. 

Longer answer: to be honest I don't know much about RSS so I'd have to look into it; could you suggest a way how it would work (not the implementation, more how it would look like) and I'll look into it? 
I think one other thing that's missing and that would have to go in that mix is chronological posts (which is what Hugo or Jekyll support by default I think). I don't think it's very hard but I just need to think about it would work.  

Anyway, I suspect RSS works by feeding a list of pages in some order with some date, so there's a question on how to build that list automatically, there's a natural way to do this, with "general pages" I guess the user would have to specify an order. 

I'll do a bit of reading on how RSS works and if you give me a few extra ideas we can see how it could come to be implemented nicely for JuDoc?

Thanks!

**Comment by cormullion** [comment]
Question was prompted by some comments on the Julia slack:

=======================================================
>Valentin Churavy [23:56]
>I dislike Julia bloggers because it destroys formatting

>Michael K. Borregaard [07:17]
>I use it for discovery but always click to the original post

>Mauro Werder [13:40]
>Yep, it would be more useful to just show the title and a link.

>Matt Bauman [17:56]
>Maybe better for SEO, too?  Wholesale copying of content is a great way to tank your search engine ratings.  I know nothing about SEO. So: :mountain::salt:

>Lyndon White [18:01]
>My CSS skills kinda suck, so I actually find that JuliaBloggers reposting of my content looks really great and my own site looks bad (edited) 

>hycakir [18:44]
>replied to a thread:
and a short intro/description...

>Randy Zwitch [18:49]
>replied to a thread:
This is configurable by the individual poster...if the RSS feed just provides a description, then that is what would get posted

>Randy Zwitch [18:53]
>replied to a thread:
good example here...Mat only provides a summary in his RSS, which is what gets posted
image.png 

>Mathieu Besançon [20:30]
>I think this is the default on newer hugo versions

>Mauro Werder   [May 31st at 13:40]
>Yep, it would be more useful to just show the title and a link.
14 replies

>hycakir   [3 days ago]
>and a short intro/description...

>Randy Zwitch   [3 days ago]
>This is configurable by the individual poster...if the RSS feed just provides a description, then that is what would get posted

>Randy Zwitch   [3 days ago]
>good example here...Mat only provides a summary in his RSS, which is what gets posted
image.png 

>hycakir   [3 days ago]
>Thanks for the info. My reply was to the suggestion of just title and link.

>hycakir   [3 days ago]
>I believe the current situation (leaving the decision to the poster) can make things hard especially for mobile visitors, for example, when you enter juliablogger and try to scroll...

>Mathieu Besançon   [2 days ago]
>I had no idea I did this :sweat_smile:

>Randy Zwitch   [17 hours ago]
>@ hycakir The whole point of JuliaBloggers to me is effortless discovery. It’s literally a WordPress plugin that reads RSS feeds and auto-posts tweets. Anything more than that becomes an exercise in me being the editor of a website and making editorial decisions, which I have no desire to do

>Eric Forgy   [16 hours ago]
>My one wish for JuliaBloggers is to include the date of the original article. I often see a cool title, click it and discover I already read it a year ago :sweat_smile:

>Eric Forgy   [16 hours ago]
>(but generally think it is cool so thank you :blush: )

>Randy Zwitch   [16 hours ago]
>do you mean for Twitter?

>Randy Zwitch   [16 hours ago]
>if so, it should only be re-posting articles 90 days or newer...except in the cases where people change their site, which resets their RSS feed. Then things look like they are new, which is hard to defend against

>Eric Forgy   [16 hours ago]
>Yeah. Twitter. It happpend fairly frequently (at least in my experience), but if it is due to an action on the orignial article beyond your control, then no worries. It would definitely be nice if the tweet contained the original date published though :slightly_smiling_face:

>Randy Zwitch   [16 hours ago]
>It’s probably a simple fix if someone knows PHP :joy:

>Eric Forgy   [16 hours ago]
>Is the source online somewhere? I've never touched PHP, but would be willing to give it a try to add a date :blush: (edited)

>Randy Zwitch [15:30]
>replied to a thread: @ hycakir The whole point of JuliaBloggers to me is effortless discovery. It’s literally a WordPress plugin that reads RSS feeds and auto-posts tweets. Anything more than that becomes an exercise in me being the editor of a website and making editorial decisions, which I have no desire to doView newer replies If JuliaBloggers causes everyone this much heartburn, I’m happy to transfer the domain name to whomever wants to take over and make it into something that the community feels is better

>Lyndon White [15:49]
>Yeah, nah. It's good.

>Michael K. Borregaard [16:01]
>JuliaBloggers is great. there will always be people who wish for tweaks or things to be different

>Randy Zwitch [16:06]
>sorry, I didn't mean for that to come off like I was hurt....more of just a reflection of it's not my baby or anything. Just something that I did because the $30/yr is trivial to me relative to giving something back to the community so if someone has time to put into it, I'm happy to accept help or transfer things over

>Patrick Mogensen [19:22]>
>Fwiw I think it’s great. I always click the link anyway

====================================================================

So it seems that the RSS feed should basically just show the first paragraph and the (prominent) date, and a working link, and avoiding a full dump or anything that might not render correctly when the RSS is re-displayed. Speaking for myself, the first picture would be nice... :)

On my old Jekyll site, I had no idea what was being automatically generated (it was probably incredibly configurable) - now that I look, it appears to consist of this line in the header:

`<link type="application/atom+xml" rel="alternate" href="http://localhost:4000/feed.xml" title="cormullion" />`

(may have looked different back in the day) and a complete dump of everything it could find in every post into:

`https://github.com/cormullion/cormullion.github.io/blob/master/_site/feed.xml`

which was probably too much...

**Comment by tlienart** [comment]
Ok great, yeah it seems reasonable that you wouldn't want some huge piece of unformatted KaTex in the feed... Probably a variable to be able to manually adapt whatever gets shown could be exposed as well.

Thanks for this, I'll look into it.

Ps: I wasn't aware of Juliabloggers so that definitely motivates this FR!

**Comment by tlienart** [comment]
Ok so I've now looked a bit more into this (btw JuliaBloggers is down?)

What is required is:

1. have a XML file
2. add entries in that XML file with some specific formatting and dates for when the thing was published and when the thing was last updated (I guess could get this via file stats)
3. add the content of the page 

One thing to bear in mind is that the content is not styled (CSS) so I guess what makes more sense is to have a`@def` variable for the RSS a bit like an "abstract" of the page which would be in markdown format but with warning that it should be pretty barebones, maths would not be ok (CSS missing)

pages that don't have that would not be recorded in the RSS feed which I guess would be fair enough.

**Comment by cormullion** [comment]
Sounds great! I think you don't want to include the entire page, just the first teaser paragraph then a "continue reading over at ..." link. JuliaBloggers (currently down but not out), for example, render the entire posts, but because they don't have the right formatting etc. the posts would be better read _in situ_. As you might guess, I'd quite like if the first image was included too, since a visual taster is often a good incentive to follow the link.

**Comment by cormullion** [comment]
Great stuff! I'm on it. Well, actually, I've made a start updating some of my posts to Julia v1.0 (remember `contains`?) and then try out the new RSS settings. It make take some time, so don't wait for me... :)

**Comment by tlienart** [comment]
Oh sure no worries, I'll mark this as experimental anyway  and do some testing by myself but feedback (inc. for namings and general workflow) will be very welcome in their own time. Good luck with the updating :D

**Comment by tlienart** [comment]
So I tried it with Vienna and it seems to work as expected:

<img width="758" alt="Screen Shot 2019-10-01 at 15 46 03" src="https://user-images.githubusercontent.com/10897531/65967921-b53b4880-e462-11e9-9ba7-886a7a0a353f.png">

I need to add an automatic link "read more here ..." to be added at the end of description but otherwise I'm reasonably happy for now 🙂
