### ISSUE TITLE
Kwarg for the path of the built page?

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/JuDoc.jl#185]
I'm wondering if it would be possible to add a keyword argument to specify the path of the generated pages. The use-case is GitLab pages, where everything must be in the `public/` directory (so it should be `public/index.html`, `public/pub/` and `public/css/`). 
Two solutions (that I know) for that:
1. put everything into the `public/` folder.
2. use Gitlab CI/CD: `mv index.html public/index.html` etc.

Former has the downside that every file can be accessed specifying the full path, latter is totally fine.
How hard would it be to add a kwarg like `publish(;buildpath="")`? I checked the source code and did not really know where it should go (otherwise this would be a PR not an issue :D ).

**Comment by cserteGT3** [comment]
I just went through the docs, and realized that this would probably conflict with `cleanpull()`. Maybe option 2 should be an "official" way to use JuDoc with GitLab pages?
(I'll add some notes on GitLab to the docs once I've "finished" porting my site)

**Comment by tlienart** [comment]
Hey! I’ve played with Gitlab pages a while back but don’t remember exactly how it’s all supposed to look. Would you have a link to a website 101 example repo that I could have a look at to see what needs adapting?

If you just copied and pasted the current folder in a `public/` subfolder would that just do the trick? Seems a bit silly

There are two thing I’d need to check once I have a better idea of how things on gitlab work:

1. What the folder should look like before pushing to gitlab
2. What relative links look like on gitlab, is it the same as on github ie the root is `username.gitlab.io` and then the site is at `username.github.io/index.html`?

Another thing maybe to check is how Hugo deals with it: does it put everything in a public subfolder and if so does it adapt the live server? Seems like unnecessary work...

Anyway I’m travelling for the next couple of days but will investigate this ASAP, thanks for bringing it up!

**Comment by cserteGT3** [comment]
I'll try and answer for everything:
Firstly [the requriements](https://docs.gitlab.com/ee/user/project/pages/introduction.html#user-or-group-pages):
* Domain of the instance: domain name that is used for GitLab Pages. (Foruser pages that is username.gitlab.io)
* GitLab CI/CD: a `.gitlab-ci.yml` file with a specific job named [pages](https://docs.gitlab.com/ee/ci/yaml/README.html#pages) in the root directory of your repository.
* A directory called `public/` in your site’s repo containing the content to be published.
* GitLab Runner enabled for the project.

[Simple HTML](https://gitlab.com/pages/plain-html) and [Hugo](https://gitlab.com/pages/hugo) example repos.

> If you just copied and pasted the current folder in a public/ subfolder would that just do the trick? Seems a bit silly
> There are two thing I’d need to check once I have a better idea of how things on gitlab work:
> 1. What the folder should look like before pushing to gitlab

Yes. The easiest way to do is keeping everything as-is and use the following `.gitlab-ci.yml`:
```
# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
```
This copies the everything into a `public/` folder when the CI/CD runs.

>2. What relative links look like on gitlab, is it the same as on github ie the root is username.gitlab.io and then the site is at username.github.io/index.html?

I don't have a deep understanding of this, but for user pages it's the same as github (username.gitlab.io/index.html). For project pages, etc. I will just put a [link](https://docs.gitlab.com/ee/user/project/pages/getting_started_part_one.html) here.

**Comment by cserteGT3** [comment]
My personal note on this script:
> Yes. The easiest way to do is keeping everything as-is and use the following `.gitlab-ci.yml`:
> 
> ```
> # This file is a template, and might need editing before it works on your project.
> # Full project: https://gitlab.com/pages/plain-html
> pages:
>   stage: deploy
>   script:
>     - mkdir .public
>     - cp -r * .public
>     - mv .public public
>   artifacts:
>     paths:
>       - public
>   only:
>     - master
> ```
> 
> This copies the everything into a `public/` folder when the CI/CD runs.

I moved my user page to GitLab, because there private repos can publish pages too (unlike now on GitHub). I want to hide the source of one page, which is generated from sensitive data. (I only want to publish the plots like in [JuDocPlottest](https://github.com/cserteGT3/JuDocPlottest), not the source `.csv` file. Btw this page is not live yet.)
As I understand from the docs, the folders that are needed for the published page are: `css/`, `pub/` and maybe `libs/`? And ofc `index.html`.
Therefore my proposed `.gitlab-ci.yml`:
```
pages:
  stage: deploy
  script:
    - mv css public/css
    - mv pub public/pub
    - mv index.html public/index.html
    - mv libs public/libs
  artifacts:
    paths:
      - public
  only:
    - master
```

**Comment by tlienart** [comment]
Looks good to me (though you also want to `mv assets public/assets` (*)). I'll try setting up a public simple example repo oon Gitlab with all this soon so that it can just be cloned and copied by others. 

(PS: what you describe with hidden data makes sense, though then you'd have to make sure that you filter the `assets` folder adequately so that only generated assets are made public (e.g. images) while data ones are not. I guess you could simply add in the script a line that removes anything that has `.csv`, `.tsv`, `.dat` or whatever somewhere in `public/`).

**Comment by cserteGT3** [comment]
Thanks, I forgot about the images. I'm thinking on putting the private data to something like: `assets/privatedata`, which can be easier deleted.

**Comment by tlienart** [comment]
Ok so using your script I was able to get an example running just fine: http://tlienart.gitlab.io/ 

I'll add this to the doc & explain also the trick where you remove sensitive files if you don't want those to be in the public folder. Thanks!
