### ISSUE TITLE
Inject markdown text from file

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/JuDoc.jl#193]
I'm still a bit confused on inserting text files, sorry if the answer is already described in the docs.
So I'd like to insert a table, which is in markdown (in the assets folder). Is it possible to "inject" it in a page with a command?

**Comment by cormullion** [comment]
I think, if you can write out to a file, you can then read it in automatically. https://tlienart.github.io/JuDoc.jl/stable/man/syntax/#Plain-text-output-1 

But that's not for capturing stdio output, I think... (not too sure...)

**Comment by cserteGT3** [comment]
Thanks for the suggestion! Now I had time to play around with it, and the following worked (only relevant parts shown):
in `index.md`:
```
\textoutput{private/test}
```
and the markdown file's path:
```
assets/private/output/test.out
```
It's not that convenient (that it requires one more directory and other extension), but totally works.

What you've suggested (`\input{output}{private/test}`) also works with the above path, but inserts the file in a code block.

**Comment by cserteGT3** [comment]
Okay, that is weird:
I use the above command to insert the file (`\textoutput{private/test}`) and as far as I understand, I need to have the `test.out` file in the `assets/private` folder and in `assets/private/output` too. Here are some attempts and the corresponding error messages (after every modification I run `serve()`):

Directories and files:
```
assets/
	private/
			test.out                     
```
Result:
```julia
julia> serve()
→ Initial full pass...

... error processing 'index.md' in ...BenchmarkResults\src.
Verify, then start judoc again...

err = ErrorException("I found an \\input but no relevant output file.")
-1
```

Directories and files:
```
assets/
	private/
			test.out
	output/       
```
Result:
```julia
julia> serve()
→ Initial full pass...

... error processing 'index.md' in ...BenchmarkResults\src.
Verify, then start judoc again...

err = ErrorException("I found an \\input but no relevant output file.")
-1
```

Directories and files:
```
assets/
	private/
			test.out
	output/
			test.out
```
Result (this works):
```julia
julia> serve()
→ Initial full pass...
→ Starting the server...
✓ LiveServer listening on http://localhost:8000/ ...
  (use CTRL+C to shut down)
```
Directories and files:
```
assets/
	private/
	output/
			test.out
```
Result:
```julia
julia> serve()
→ Initial full pass...

... error processing 'index.md' in ...BenchmarkResults\src.
Verify, then start judoc again...

err = ArgumentError("Couldn't find a relevant file when trying to resolve an \\input command. (given: private/test)")
-1
```

So it seems that I have to have the file at both places for this method. I modified the files, and the `assets/private/output/test.out` one gets processed

**Comment by tlienart** [comment]
Hello! sorry, a few weeks of hectic over here and haven't managed to work much on the project. 

So if I understand well you have:

1. a side file `sidefile.md` 
2. that you want to insert in `index.md` so that the whole thing gets parsed and processed by JuDoc.

So for instance you'd have in `sidefile.md` 

```markdown
### side file
$$ 1+1 = 2 $$
Done
```

And in `index.md`

```markdown
The index
\insert{path/to/sidefile.md}
```

so that the overall effect would be as if you had written

```markdown
The index
### side file
$$ 1+1 = 2 $$
Done
```

Can you confirm that's what you'd like?

### way forward

Assuming that's what you want then `\textoutput` is not really the way to go, it's more meant to go with the output of a julia script in the context of the evaluation of a code block.

So it would need to be another command like

```
\input{path/to/file.md}
```

which would plug the markdown in place. This would work a bit like `\textoutput` (which implicitly uses the function `resolve_lx_input_plainoutput` see https://github.com/tlienart/JuDoc.jl/blob/master/src/converter/lx.jl#L257_L266) except that it would take the path "as is" so the 

* line 260 would change (and would try adding a `.md` instead of `.out` if there isn't one already)
* line 264 would be removed

I can probably get that done by tomorrow.

**Comment by cserteGT3** [comment]
> Hello! sorry, a few weeks of hectic over here and haven't managed to work much on the project.
> 
> So if I understand well you have:
> 
> 1. a side file `sidefile.md`
> 2. that you want to insert in `index.md` so that the whole thing gets parsed and processed by JuDoc.
> 
> So for instance you'd have in `sidefile.md`
> 
> ```gfm
> ### side file
> $$ 1+1 = 2 $$
> Done
> ```
> 
> And in `index.md`
> 
> ```gfm
> The index
> \input{path/to/sidefile.md}
> ```
> 
> so that the overall effect would be as if you had initially written in `index.md`
> 
> ```gfm
> The index
> ### side file
> $$ 1+1 = 2 $$
> Done
> ```
> 
> Can you confirm that's what you'd like?

Yes, exactly!

> ### way forward
> Assuming that's what you want then `\textoutput` is not really the way to go, it's more meant to go with the output of a julia script in the context of the evaluation of a code block (and it gets confused if it doesn't find a pair of script file + output file)
> 
> So it would need to be another command like
> 
> ```
> \input{path/to/file.md}
> ```
> 
> which would plug the markdown in place. This would work a bit like `\textoutput` (which implicitly uses the function `resolve_lx_input_plainoutput` see https://github.com/tlienart/JuDoc.jl/blob/master/src/converter/lx.jl#L257_L266) except that it would take the path "as is" so the
> 
> * line 260 would change (and would try adding a `.md` instead of `.out` if there isn't one already)
> * line 264 would be removed
> 
> I can probably get that done by tomorrow; the only thing I'll need to check is that it doesn't clash with how `\input` currently works.

Awesome! Thank you very much!

**Comment by tlienart** [comment]
Ok so the `\textinput` command should do what you want. 

Screenshot of the relevant doc section:

<img width="827" alt="Screen Shot 2019-08-06 at 11 38 39" src="https://user-images.githubusercontent.com/10897531/62529340-c559f180-b83e-11e9-8cb5-12835629b0ba.png">

Could you please check it does what you expect? thanks!

**Comment by cserteGT3** [comment]
That is exactly what I wanted! Thank you very much again!
