### ISSUE TITLE
RSS enhancements [feedback welcome]

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#246]
I'll leave this open for people to comment; current support is experimental.

### Would be nice to add

* [x] automatic "read more at ..." added at the end of description, maybe with a horizontal separator.

**Comment by cormullion** [comment]
Looks great - working without any problems here... 

<img width="1311" alt="Screenshot 2019-10-02 at 17 26 43" src="https://user-images.githubusercontent.com/52289/66062794-fb171000-e539-11e9-9157-58cfbb1e750e.png">

So, thanks!

I might add RSS links to the julialangblog mirror too, later this week, perhaps...

**Comment by tlienart** [comment]
Beautiful, this makes me happy!
