### ISSUE TITLE
Markdown reference links

### ISSUE THREAD

**Issue by cormullion** [tlienart/JuDoc.jl#250]
As I updated the RSS stuff [here](https://julialangblogmirror.netlify.com) I noticed that the `[][]` links weren't working.

<img width="400" alt="Screenshot 2019-10-04 at 18 34 07" src="https://user-images.githubusercontent.com/52289/66227701-98f31200-e6d5-11e9-9e59-3c17f8b32e9e.png">

[Markdown source](https://raw.githubusercontent.com/cormullion/julialangblog/master/src/pages/2018-02-21-gsoc2018-numfocus.md)

I hope I didn't break anything... ?

**Comment by tlienart** [comment]
Oh! Hmm 🤔 I cannot reproduce on my branch. But on the other hand I've just done a fair bit of work on JuDoc while traveling over the last few days and may have fixed a few things along the way; would you mind pulling master and trying again? Sorry about that!

<img width="711" alt="Screen Shot 2019-10-07 at 12 25 40" src="https://user-images.githubusercontent.com/10897531/66304506-a12d9600-e8fd-11e9-81bb-b097bc060e0d.png">

**Comment by tlienart** [comment]
oh but it's the julia blog thing!  I'll have a look myself then

**Comment by tlienart** [comment]
Lol, it's an easy fix; actually the link fixer thing that took care of this was just not called on the first pass on all pages; if you modify one word then...

<img width="260" alt="Screen Shot 2019-10-07 at 12 53 32" src="https://user-images.githubusercontent.com/10897531/66306283-80ffd600-e901-11e9-9d7b-515596ede5f5.png">

Well I prefer easy fixes anyway 😋
