### ISSUE TITLE
More integrated support for Literate.jl

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#256]
If using JuDoc to write a large bunch of tutorials (and maintain those) it's probably a better idea to use a combination of Literate.jl and JuDoc. One key advantage being that Literate offers the possibility to just generate a notebook which people may like.

JuDoc already works with Literate but the support could be more integrated:

* allow insertion of literate.jl script in a judoc page, would allow avoiding to blend literate-compatible markdown and judoc markdown which, for instance, would be preferrable when supporting a notebook generation
* 

(brainstorm ongoing, ideas welcome)

**Comment by cormullion** [comment]
I think this will be great! I've always wanted to be able to include output automatically...

**Comment by tlienart** [comment]
#257 is about to be merged :-)
