### ISSUE TITLE
Use NodeJS.jl

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#262]
Might solve a bunch of annoying small issues with trying to tell Julia where node is and where modules are.

https://github.com/davidanthoff/NodeJS.jl

**Comment by adigitoleo** [comment]
Small note that NodeJS.jl has been stale for a year and the dev intended to remove the package in favour of the .jll package. See https://github.com/davidanthoff/NodeJS.jl/issues/58. Maybe the default for Franklin could be updated.

**Comment by tlienart** [comment]
Thanks for that note, NodeJS.jl is removed in the upcoming version (too many issues with the js packages in general, not specifically with NodeJS so I removed a lot of that logic) but it's good to know about the jll which I'll be glad to try.
