### ISSUE TITLE
Can't exit with ctrl+c

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/JuDoc.jl#321]
I don't have an MWE for this, but after running `serve()` I can not exit with ctrl+c, and not even kill julia with ctrl+d.
I'm on `v0.3.10` with Julia `Version 1.3.0-rc4.1` and Windows 10.
Do you have any idea why this happens?

**Comment by tlienart** [comment]
Hmm that's annoying, sorry! do you use Juno? or the REPL? And is this a freak event or something you've hit multiple times?

I believe this is unrelated to JuDoc, it's more a thing with LiveServer and working out how CTRL+C is propagated to running processes. But LiveServer hasn't been changed significantly in the last few months. Sometimes you might have to hit CTRL+C twice but I haven't seen the case that I just can't kill the server...

So I would suspect this may be an issue with CTRL+C and windows but not sure.

**Comment by cserteGT3** [comment]
Sorry, it was hasty to post the issue, without any reproducible example. I use the REPL (in this case). Ctrl+c was always a weird thing in julia, does not work reliable for me. When I wrote the issue, it happened multiple times that I only could kill the server with closing the command line (nor multiple Ctr+c or Ctrl+d worked). But now (nothing has changed, just two hours later) it works nicely.

So I guess it's rather a windows and julia issue, sorry for the noise (I'll close this issue).
