### ISSUE TITLE
Including html file

### ISSUE THREAD

**Issue by cserteGT3** [tlienart/JuDoc.jl#322]
This time I want to use PlotlyJS (and its interactive plots) and can't figure out how to insert the generated html into a page. Did I miss a command that is for this purpose? Or should I write my own? 😄 😄 

PS: what do you find a better option?

1. Adding `plotly-latest.min.js` to `/libs` or
2. Download on the fly (https://plot.ly/javascript/getting-started/)

**Comment by tlienart** [comment]
So  to insert HTML on a  page, just do  

```md
~~~
THE HTML
~~~
```

if it's  generated and  in a  file `myhtml.html` you  can also do

```md
some markdown
~~~
{{insert path/to/myhtml.html}}
~~~
```

I'll try to come up with a working example with Plotly  later, it's a good idea :-)

**Comment by tlienart** [comment]
Ok here are simple steps to  a working example.

1. (optional) create a new website

```julia
newsite("plotly", template="sandbox")
```

2. download the `plotly`  file from https://plot.ly/javascript/getting-started/, put it in `/libs/plotly/plotly.min.js` 

then

3. modify `src/_html_parts/head.html` to  have the lines (the first 2 are already  there, just  add  the 3d one)

```julia
{{if hasmath}} {{insert head_katex.html }}     {{end}}
{{if hascode}} {{insert head_highlight.html }}   {{end}}
{{if hasplotly}} <script src="/libs/plotly/plotly.min.js"></script> {{end}}
```

4. in `src/index.md` add 

```markdown
## Plotly

~~~
<div id="tester" style="width:600px;height:250px;"></div>

<script>
	TESTER = document.getElementById('tester');
	Plotly.plot( TESTER, [{
	x: [1, 2, 3, 4, 5],
	y: [1, 2, 4, 8, 16] }], {
	margin: { t: 0 } } );
</script>
~~~

Now if you `serve()` you  get

<img width="769" alt="Screen Shot 2019-12-25 at 11 25 34" src="https://user-images.githubusercontent.com/10897531/71443088-4d1a9c80-2709-11ea-9893-935df12b673a.png">

```

**Comment by tlienart** [comment]
Now something even fancier is to  have Julia code generating the plot in your markdown, there's a few more steps but it shouldn't be much more difficult. I'll get back soon with an  example
