### ISSUE TITLE
[requesting suggestions] Name change

### ISSUE THREAD

**Issue by tlienart** [tlienart/JuDoc.jl#338]
Hello everyone & happy new year!

I've got good and bad-ish news: the good is that in some near-ish future, the Julia website _may_ be written using this package which would be awesome. The bad-ish news is that the name of the package is a bit awkward which I've been kindly made aware of recently; as everyone knows, naming stuff well is hard! 

So I'm open to suggestion as to  how to rename this package 😄 there's already Jekyll, Hugo, Octopress, Zola, Pelican, Docusaurus, Gatsby, ... (and [many, many others](https://www.staticgen.com/)) so what shall it be for this one?

Here are a few candidates in no particular order to get the ball rolling

- Camus
- Hyde
- Wombat
- Hippo
- BloggyMcBlogFace (please don't)
- Wakanda
- Kayak 

I'll aim to rename the package by March (I'll then need a bit of time to refactor things accordingly).

also cc @cserteGT3 @cormullion @asprionj

**Comment by ViralBShah** [comment]
I like Hyde, as in Dr. Jekyll and Mr. Hyde. But perhaps being a 4 letter name, it might have a problem with approval for the registry?

**Comment by ViralBShah** [comment]
I think we may want to also consider getting a domain name for the new name. Or at least think about it.

**Comment by ararslan** [comment]
> But perhaps being a 4 letter name, it might have a problem with approval for the registry?

I believe that only applies for auto-merging; it could still be manually merged by a maintainer.

**Comment by ViralBShah** [comment]
@ararslan Is that only for the first time, or for every new version?

**Comment by tlienart** [comment]
> I think we may want to also consider getting a domain name for the new name. Or at least think about it.

an advantage of having ".jl" in package names means that `namejl.ext` makes sense and is also likekly to be available (jekyll did this with `jekyllrb.com`). For instance `hydejl.io/com/org` are available afaict.

**Comment by logankilpatrick** [comment]
It’s every version I think

**Comment by ararslan** [comment]
> Is that only for the first time, or for every new version?

No, only the first time. For reference, I haven't had any issues registering new versions of [EDF.jl](https://github.com/beacon-biosignals/EDF.jl) after the initial registration.

**Comment by cormullion** [comment]
Interesting! But very difficult to think of a name without knowing some restrictions. Do you want it to link somehow to Julia, blogging, web pages, ... or do you just want a cool name that doesn't mean anything in particular?  

I don't think you can have [Hyde](https://github.com/hyde/hyde) anyway, even if you really wanted to say "this isn't Jekyll"...

Fun places to look for names include [Godchecker](https://www.godchecker.com), [Typefaces](https://en.wikipedia.org/wiki/List_of_typefaces) (associations with publishing), [WordHippo](https://www.wordhippo.com) for synonyms, [Chemical elements](https://en.wikipedia.org/wiki/List_of_chemical_elements), etc. Or the classic "Combine a color and an animal" ploy? :)

**Comment by StefanKarpinski** [comment]
I do think a rename is a good idea, too bad (but not surprising that Hyde is already taken), bit I’m sure we can come up with something even better!

**Comment by logankilpatrick** [comment]
Thoughts on just “JDocs”

**Comment by ararslan** [comment]
I typically associate the prefix J with Java-related software.

**Comment by StefanKarpinski** [comment]
Why is it important for the name to indicate Julia?

**Comment by ViralBShah** [comment]
Packages already have the `.jl` suffix, so having a J or Ju in the name is a bit redundant.

**Comment by cormullion** [comment]
A few more suggestions

*Justina* - *Ju*lia *St*atic, er, *In*ternet, er... *A*ssistant 🤪
*Baskerville* - sort of publishing, text, words (and there’s a subtle link to Hugo)
*Franklin* - could be publishing-ey, but why not remember scientist Rosalind as well?
*Despatch* - but I can never spell that, so there’s that

I’m slightly unsure of “docs” in the name, because, well, it’s more than that.

**Comment by tlienart** [comment]
Yeah no need for docs or explicit ref to Julia, I guess at the onset it kind of made sense to me but now I like the idea of just picking an easy-to-remember name. Thanks for the suggestions @cormullion! I like Franklin, less so the other ones; I'm also tempted by wombat which is a weird but fun animal, or kayak because it's got 2 ks. Thanks for the fun links too, I'll play with them :)

**Comment by ViralBShah** [comment]
From @cormullion 's list, I like Franklin the best.

**Comment by randyzwitch** [comment]
I like Franklin as well

**Comment by StefanKarpinski** [comment]
Franklin is pretty good but it will probably be assumed to be named after the more famous Franklin—Benjamin. Perhaps Rosalind would be a good name to honor her specifically? Too familiar?

**Comment by tlienart** [comment]
Yeah I thought so too... but then if we're going with first names and possibly  in the vein of cool scientist, we could also go with Emmy which is easier to write than Rosalind. But then again people may think about like... the emmys... jeez. Tao.jl?

**Comment by ararslan** [comment]
Tao.jl may be confused with [Tau.jl](https://github.com/JuliaMath/Tau.jl) and/or [Yao.jl](https://github.com/QuantumBFS/Yao.jl).

**Comment by tlienart** [comment]
Hahaha 🙈 , how about `Zeno.jl` ? (with an allusion to the package's recursive parsing ability).

**Comment by cserteGT3** [comment]
+1 for `Franklin`, or what about `DrFranklin` (like [DrWatson.jl](https://github.com/JuliaDynamics/DrWatson.jl))? I like `Rosalind` as well, and don't find hard to write it.

**Comment by cormullion** [comment]
Good (and paradoxical) idea! There are a few hits on Github's repo list, but nothing too close...

I thought Tolkien might help with some meaningless and pleasant-ish words:

- Eldarin
- Amandil
- Vanyarin 
- Irithiel 
- Quamara
- Talindra

etc. Plenty still to be claimed for a Github repo. But it's amazing how many words have already been used for projects...

**Comment by StefanKarpinski** [comment]
Looking at words that are printing-related, I came up with these ideas:

* [Codex](https://en.wikipedia.org/wiki/Codex)
* [Vellum](https://en.wikipedia.org/wiki/Vellum)
* [Albion](https://en.wikipedia.org/wiki/Albion_press)
* [Flexo](https://en.wikipedia.org/wiki/Flexography)
* [Paige](https://en.wikipedia.org/wiki/Paige_Compositor)
* [Hellbox](https://en.wikipedia.org/wiki/Hellbox)
* [Forme](https://en.wikipedia.org/wiki/Forme_(printing))
* [Chase](https://en.wikipedia.org/wiki/Chase_(printing))
* [Letterpress](https://en.wikipedia.org/wiki/Letterpress_printing)
* [Quoin](https://en.wikipedia.org/wiki/Quoin_(printing))
* [Dingbat](https://en.wikipedia.org/wiki/Dingbat)
* [Prepress](https://en.wikipedia.org/wiki/Prepress)
* [Platen](https://en.wikipedia.org/wiki/Platen)
* [Frisket](https://en.wikipedia.org/wiki/Frisket)
* [Tympan](https://en.wikipedia.org/wiki/Tympan)


I would also note that perhaps `Franklin` is good and can be considered to honor both Rosalind Franklin and Benjamin Franklin, as the latter worked as a [printer's devil](https://en.wikipedia.org/wiki/Printer%27s_devil) in his youth and became a very famous writer as well as inventor.

**Comment by ararslan** [comment]
Windings.jl :trollface:

**Comment by tlienart** [comment]
thanks so much for all the help! Sounds like Franklin gets a majority here, I may let this sit a while and then do the necessary refactoring. 

In terms of refactoring btw, can I just rename the repo and re-register it or am I safer to start a new repo from zero?

**Comment by StefanKarpinski** [comment]
The best approach at the moment is to change the repo name, change the UUID and re-register.

**Comment by ViralBShah** [comment]
@tlienart If it is possible for you, may I suggest renaming the repo and registering the new name now rather than later? Perhaps some of us can even help with what is required here, and may be a good way to get a few more people engaged with the project in a small way.

**Comment by tlienart** [comment]
> The best approach at the moment is to change the repo name, change the UUID and re-register.

@StefanKarpinski short question: if I do that what will happen to current users when they do `up`? they'll keep having the last minor release (0.4) of 'JuDoc'? so I can do the following steps without breaking people's code and release a `Franklin` 0.5 which they could then hook on to later?

(FWIW the package doesn't export any function that are likely to be used by other packages as a dependency so unless I miss something it should be ok to proceed). 

Thanks! (and thanks everyone else for input 😄 )

**Comment by StefanKarpinski** [comment]
Current users won't get upgrades: they'll just stay on the last version registered as JuDoc. Franklin will appear as an entirely new, unrelated package. They can upgrade by doing `] rm JuDoc` and `] add Franklin` and then search and replacing `JuDoc` with `Franklin`.

**Comment by asprionj** [comment]
Sorry, late to the party. Just thought about [GatsbyJS](https://www.gatsbyjs.org/); so what about Carraway (the narrator in _The Great Gatsby_), or Buchanan (surname of Daisy, the love of Gatsby, but also of his adversary who got her first...)?

Anyway, I think Franklin is a good choice.

**Comment by tlienart** [comment]
Thanks all! I'll definitely name future themes in honour of the many great suggestions here but it seems that Franklin just works well for everyone so let's just roll with that. I'll close the issue  and  will try to do that by the weekend or something 😸

**Comment by cserteGT3** [comment]
> Current users won't get upgrades: they'll just stay on the last version registered as JuDoc. Franklin will appear as an entirely new, unrelated package. They can upgrade by doing `] rm JuDoc` and `] add Franklin` and then search and replacing `JuDoc` with `Franklin`.

Is it possible to "deprecate" the package in a 0.5 release by printing a warning that the name has changed?

**Comment by tlienart** [comment]
yeah I'll do that in a registered `0.4.1` release 👍

**Comment by cormullion** [comment]
@asprionj Nice names! Like so many such, there's already a few Github hits - because Gatsby is a thing, Carraway is also a thing, I suppose. A few hits for Buchanan too. Wonder how soon we'll run out of decent names?
