### ISSUE TITLE
Allow include utils.jl also for all markdown julia

### ISSUE THREAD

**Issue by schlichtanders** [tlienart/JuDoc.jl#912]
I face difficulties using `@def` and `+++ ... +++`.

`utils.jl` is not available in the scope and it seems the only way to add further julia utilties is by adding commands on top of each markdown like
```
+++
using Markdown
myvar = md"""
some markdown string
"""
+++
```
That is nice, however it would be really intuitive to have utils.jl available by default everywhere.

**Comment by schlichtanders** [comment]
I think I understood the issue
I was trying to parse my markdown variable directly to html like
```
+++
myvar = mytohtml("""
""")
+++
...
```

And found in the web that `Franklin.fd2html` actually works pretty well for this case.
So I tried it but looking now into the source code of that function, it should be named `fd2html!` because it modifies global Franklin state, which I guess breaks everything.
Trying to solve this separately

-----------------


In this regard [my original attempt](https://github.com/tlienart/Franklin.jl/issues/912#issuecomment-947514780) actually works in general.
Still it would be nice to have utils.jl automatically available

**Comment by tlienart** [comment]
Here's a fuller example along the lines of what I think you're doing

`utils.jl`:
```julia
using Markdown

function hfun_uncover(p)
  v = locvar(p[1])
  Markdown.html(v)
end
```

`page.md`
```
+++
title = "Franklin Sandbox"
b = Franklin.utils_module().@md_str("""
  Hello **bye**.
  """)
+++

{{uncover b}}
```
